CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -g
CXXFLAGS += -pedantic-errors

SRCS = Lab4.cpp

CLN = Lab4 results.txt

default:
	${CXX} ${CXXFLAGS} ${SRCS} -o Lab4

clean: 
	rm -f *.o *~ ${CLN}
